spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.52.87.226:3306/smbms?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: Ll#3771056
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: pro


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kgc.chinaautorental

logging:
  level:
    com.kgc.springboot_smbms.dao: info

